### ISSUE TITLE
PSU item

### ISSUE THREAD

**Issue by poundy** [hwstar/esp12-appliance_mod#1]
It would make sense to list an item # for an eBay PSU unit that you had used, for reference.  In either Readme or BOM would work.

**Comment by hwstar** [comment]
I bought 5 of them under ebay item #351211320656. This seller has since re-listed a similar power supply under a new item number which Ebay will direct you to. The board is laid out with a hole spacing of 1.79 in. by 0.675 in. The power supplies I received are 2.037 in. long by 0.930 in. wide and have 4 mounting holes.
